# fly.toml app configuration file generated for splash-ui on 2024-01-17T14:19:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "splash-ui"
primary_region = "ams"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
